### PR TITLE
Resolution with Promises; optional arguments for resolution/rejection; finally(); comments

### PR DESCRIPTION
**Pull request by myurasov**
- Fix _getThen() to allow resolving with Promises (as per https://www.promisejs.org/implementing/)
- Allow resolving/rejection without argument
- Add finally() method
- Add comments on class, file and public methods
- Added an example of resolution with another promise and finally() call

### CODE REVIEW

**Comment by blindman2k** [comment]
The changes are all good but the new example (promise inside a promise) is complex, confusing and not explained at all. I like the new finally() resolution.

**Comment by blindman2k** [comment]
Don't forget to increment the minor version number. This is adding new functionality but not breaking any existing functions, so it should be v1.1.0

**Comment by myurasov** [comment]
Agree, should be 1.1.0. Added few more explanations to the example B.

**Comment by myurasov** [comment]
Switched to git-flow and merged this into develop. Closing.

**Pull request closed without merging**
