### PR TITLE
Test coverage for Promises libraries

### PR DESCRIPTION
**Pull request by dbukhmastov**
CSE-310 - Test coverage for Promises libraries

### CODE REVIEW

**Comment by ppetrosh** [comment]
When I run tests locally they fail:
```
[+19.24/0.00s info] Starting test session scared-telephone
[+19.24/0.00s info] Test session is agent-only
[+19.24/0.00s info] Using agent test file tests/PendingState.agent.test.nut
[+19.36/0.12s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+19.49/0.13s info] Using model Test Group B [qryDFGlK1tUd]
[+20.02/0.52s info] Created revision: 64
[+20.52/0.51s info] Device code space usage: 0.5%
[+22.61/2.08s test] PendingState::testAllFinally()
[+32.34/9.74s test] Success
[+32.35/0.00s test] PendingState::testAllThen()
[+42.91/10.57s test] Success
[+42.91/0.00s test] PendingState::testLoopFinally()
[+52.74/9.83s test] Success
[+52.74/0.00s test] PendingState::testLoopThen()
[+62.52/9.78s test] Success
[+62.52/0.00s test] PendingState::testRaceFinally()
[+72.29/9.77s test] Success
[+72.30/0.00s test] PendingState::testRaceThen()
[+72.30/0.00s test] Failure: the index 'race' does not exist (line 17)
[+72.30/0.00s test] PendingState::testSerialFinally()
[+82.56/10.27s test] Success
[+82.56/0.00s test] PendingState::testSerialThen()
[+92.37/9.80s test] Success
[+92.37/0.00s test] Tests: 8, Assertions: 0, Failures: 1
[+92.37/0.00s info] Session scared-telephone failed
```
@dbukhmastov can you please give it a look?

**Comment by ppetrosh** [comment]
And this one times out:
```
[+370.71/0.00s info] Starting test session believed-particular
[+370.71/0.00s info] Test session is agent-only
[+370.71/0.00s info] Using agent test file tests/resolve/ManyResolveRejectThen_3.agent.test.nut
[+370.82/0.12s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+370.97/0.15s info] Using model Test Group B [qryDFGlK1tUd]
[+371.49/0.52s info] Created revision: 80
[+371.98/0.49s info] Device code space usage: 0.5%
[+374.02/2.05s test] ManyResolveRejectThen_3::testBasicResolving_1()
[+375.31/1.29s test] Success: ["Passed: Value='true', iState=192, RND=00","Passed: Value='false', iState=192, RND=00"]
[+375.31/0.00s test] ManyResolveRejectThen_3::testBasicResolving_2()
[+376.07/0.76s test] Success: ["Passed: Value='0', iState=192, RND=01","Passed: Value='1', iState=192, RND=00"]
[+376.07/0.00s test] ManyResolveRejectThen_3::testBasicResolving_3()
[+377.16/1.09s test] Success: ["Passed: Value='-1', iState=192, RND=10","Passed: Value='', iState=192, RND=10"]
[+377.16/0.00s test] ManyResolveRejectThen_3::testBasicResolving_4()
[+378.07/0.92s test] Success: ["Passed: Value='tmp', iState=192, RND=00","Passed: Value='0.001', iState=192, RND=00"]
[+378.07/0.00s test] ManyResolveRejectThen_3::testBasicResolving_5()
[+379.09/1.01s test] Success: ["Passed: Value='0', iState=192, RND=01","Passed: Value='-0.001', iState=192, RND=00"]
[+379.09/0.00s test] ManyResolveRejectThen_3::testBasicResolving_6()
[+380.12/1.03s test] Success: ["Passed: Value='(meta : 0x7f14597f6b40)', iState=192, RND=01","Passed: Value='(null : (nil))', iState=192, RND=11"]
[+380.12/0.00s test] ManyResolveRejectThen_3::testBasicResolving_7()
[+381.46/1.34s test] ManyResolveRejectThen_3::testBasicResolving_8()
[+382.38/0.92s test] Success: ["Passed: Value='(table : 0x7f145b667ad0)', iState=192, RND=11","Passed: Value='(function : 0x7f145b2708c0)', iState=192, RND=10"]
[+382.38/0.00s test] ManyResolveRejectThen_3::testBasicResolving_9()
[+383.30/0.92s test] Success: ["Passed: Value='(class : 0x7f1480a81980)', iState=192, RND=10","Passed: Value='(meta : 0x7f14b4bb8a90)', iState=192, RND=11"]
[+383.30/0.00s test] ManyResolveRejectThen_3::testDelayedResolving_1()
[+384.23/0.93s test] Success: ["Passed: Value='true', iState=192, RND=01","Passed: Value='false', iState=192, RND=11"]
[+384.23/0.00s test] ManyResolveRejectThen_3::testDelayedResolving_2()
[+385.45/1.23s test] Success: ["Passed: Value='0', iState=192, RND=11","Passed: Value='1', iState=192, RND=01"]
[+385.45/0.00s test] ManyResolveRejectThen_3::testDelayedResolving_3()
[+386.26/0.80s test] Success: ["Passed: Value='-1', iState=192, RND=00","Passed: Value='', iState=192, RND=10"]
[+386.26/0.00s test] ManyResolveRejectThen_3::testDelayedResolving_4()
[+387.28/1.02s test] Success: ["Passed: Value='tmp', iState=192, RND=00","Passed: Value='0.001', iState=192, RND=00"]
[+387.28/0.00s test] ManyResolveRejectThen_3::testDelayedResolving_5()
[+388.32/1.04s test] Success: ["Passed: Value='0', iState=192, RND=11","Passed: Value='-0.001', iState=192, RND=10"]
[+388.32/0.00s test] ManyResolveRejectThen_3::testDelayedResolving_6()
[+423.33/35.00s error] Testing timeout
[+423.33/0.00s info] Session believed-particular failed
```

**Comment by ppetrosh** [comment]
```
[+459.18/0.00s info] Starting test session tiny-adjective
[+459.18/0.00s info] Test session is agent-only
[+459.18/0.00s info] Using agent test file tests/ThenChain.agent.test.nut
[+459.30/0.12s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+459.43/0.13s info] Using model Test Group B [qryDFGlK1tUd]
[+459.92/0.49s info] Created revision: 94
[+460.41/0.49s info] Device code space usage: 0.5%
[+519.43/59.02s error] Session startup timeout
[+519.43/0.00s info] Session tiny-adjective failed

[+519.43/0.00s info] Starting test session property-subject
[+519.43/0.00s info] Test session is agent-only
[+519.43/0.00s info] Using agent test file tests/wrong_param/All.agent.test.nut
[+519.54/0.11s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+519.68/0.13s info] Using model Test Group B [qryDFGlK1tUd]
[+520.19/0.52s info] Created revision: 97
[+520.67/0.48s info] Device code space usage: 0.5%
[+523.08/2.41s test] All::testWrongCount()
[+523.09/0.00s test] Success
[+523.09/0.00s test] All::testWrongType_1()
[+523.09/0.00s test] Failure: Fail Resolve handler is called with value=''
[+523.09/0.00s test] All::testWrongType_2()
[+523.09/0.00s test] All::testWrongType_3()
[+523.09/0.00s test] Success: ["Pass with value='(array : 0x7f14791aad90)'","Pass with value='(table : 0x7f1478a1e5c0)'","Pass with value='(function : 0x7f1479750ab0)'"]
[+523.09/0.00s test] All::testWrongType_4()
[+523.09/0.00s test] Success: ["Pass with value='(class : 0x7f143a511470)'","Pass with value='(meta : 0x7f142c961a80)'"]
[+523.09/0.00s test] Tests: 5, Assertions: 0, Failures: 1
[+523.09/0.00s info] Session property-subject failed
```

**Comment by ppetrosh** [comment]
```
[+526.99/0.00s info] Starting test session east-aside
[+526.99/0.00s info] Test session is agent-only
[+526.99/0.00s info] Using agent test file tests/wrong_param/Fail.agent.test.nut
[+527.11/0.12s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+527.23/0.13s info] Using model Test Group B [qryDFGlK1tUd]
[+527.71/0.48s info] Created revision: 99
[+528.61/0.90s info] Device code space usage: 0.5%
[+529.98/1.37s test] Fail::testWrongCount()
[+529.98/0.00s test] Success
[+529.98/0.00s test] Fail::testWrongType_1()
[+530.76/0.78s test] Failure: Fail with value='false'
[+530.76/0.00s test] Fail::testWrongType_2()
[+530.77/0.00s test] Failure: Fail with value='0'
[+530.77/0.00s test] Fail::testWrongType_3()
[+530.77/0.00s test] Failure: Fail with value='tmp'
[+530.77/0.00s test] Fail::testWrongType_4()
[+530.77/0.00s test] Failure: Fail with value='(null : (nil))'
[+530.77/0.00s test] Fail::testWrongType_5()
[+530.77/0.00s test] Failure: Fail with value='(table : 0x7f14842f93d0)'
[+530.77/0.00s test] Fail::testWrongType_6()
[+530.77/0.00s test] Failure: Fail with value='(meta : 0x7f142c961a80)'
[+530.77/0.00s test] Tests: 7, Assertions: 0, Failures: 6
[+530.77/0.00s info] Session east-aside failed

[+530.77/0.00s info] Starting test session where-forgot
[+530.77/0.00s info] Test session is agent-only
[+530.77/0.00s info] Using agent test file tests/wrong_param/Finally.agent.test.nut
[+530.89/0.12s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+531.02/0.13s info] Using model Test Group B [qryDFGlK1tUd]
[+531.51/0.50s info] Created revision: 100
[+531.97/0.45s info] Device code space usage: 0.5%
[+534.14/2.17s test] Finally::testWrongCount()
[+534.14/0.00s test] Success
[+534.14/0.00s test] Finally::testWrongType_1()
[+534.14/0.00s test] Failure: Fail with value='false'
[+534.14/0.00s test] Finally::testWrongType_2()
[+534.14/0.00s test] Failure: Fail with value='0'
[+534.14/0.00s test] Finally::testWrongType_3()
[+534.14/0.00s test] Failure: Fail with value='tmp'
[+534.14/0.00s test] Finally::testWrongType_4()
[+534.15/0.00s test] Failure: Fail with value='(null : (nil))'
[+534.15/0.00s test] Finally::testWrongType_5()
[+534.76/0.61s test] Failure: Fail with value='(table : 0x7f1478a91e70)'
[+534.76/0.00s test] Finally::testWrongType_6()
[+534.76/0.00s test] Failure: Fail with value='(meta : 0x7f1424467d70)'
[+534.76/0.00s test] Tests: 7, Assertions: 0, Failures: 6
[+534.76/0.00s info] Session where-forgot failed

[+534.76/0.00s info] Starting test session somebody-fast
[+534.76/0.00s info] Test session is agent-only
[+534.76/0.00s info] Using agent test file tests/wrong_param/Loop.agent.test.nut
[+534.87/0.11s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+534.99/0.12s info] Using model Test Group B [qryDFGlK1tUd]
[+535.52/0.53s info] Created revision: 101
[+536.05/0.53s info] Device code space usage: 0.5%
[+538.44/2.40s test] Loop::testWrongCount_1()
[+538.44/0.00s test] Success
[+538.44/0.00s test] Loop::testWrongCount_2()
[+538.44/0.00s test] Success
[+538.44/0.00s test] Loop::testWrongFirst_1()
[+538.44/0.00s test] Agent Runtime Error: ERROR: attempt to call 'bool'
[+538.44/0.00s info] Session somebody-fast failed

[+538.45/0.00s info] Starting test session read-laid
[+538.45/0.00s info] Test session is agent-only
[+538.45/0.00s info] Using agent test file tests/wrong_param/Race.agent.test.nut
[+538.56/0.12s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+538.69/0.13s info] Using model Test Group B [qryDFGlK1tUd]
[+539.19/0.50s info] Created revision: 102
[+539.67/0.48s info] Device code space usage: 0.5%
[+542.13/2.46s test] Race::testWrongCount()
[+542.13/0.00s test] Success
[+542.13/0.00s test] Race::testWrongType_1()
[+542.13/0.00s test] Failure: Fail Resolve handler is called with value=''
[+542.13/0.00s test] Race::testWrongType_2()
[+542.13/0.00s test] Race::testWrongType_3()
[+542.13/0.00s test] Success: ["Pass with value='(array : 0x7f1444f86c00)'","Pass with value='(table : 0x7f1493bb9320)'","Pass with value='(function : 0x7f1444e4fa30)'"]
[+542.13/0.00s test] Race::testWrongType_4()
[+542.13/0.00s test] Success: ["Pass with value='(class : 0x7f145c5d9b90)'","Pass with value='(meta : 0x7f14b535da20)'"]
[+542.13/0.00s test] Tests: 5, Assertions: 0, Failures: 1
[+542.13/0.00s info] Session read-laid failed

[+542.13/0.00s info] Starting test session range-cowboy
[+542.13/0.00s info] Test session is agent-only
[+542.13/0.00s info] Using agent test file tests/wrong_param/Serial.agent.test.nut
[+542.25/0.12s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+542.37/0.12s info] Using model Test Group B [qryDFGlK1tUd]
[+542.87/0.50s info] Created revision: 103
[+543.78/0.90s info] Device code space usage: 0.5%
[+545.51/1.73s test] Serial::testWrongCount()
[+545.51/0.00s test] Success
[+545.51/0.00s test] Serial::testWrongType_1()
[+545.51/0.00s test] Agent Runtime Error: ERROR: the index 'len' does not exist
[+545.51/0.00s info] Session range-cowboy failed

[+545.51/0.00s info] Starting test session treated-part
[+545.51/0.00s info] Test session is agent-only
[+545.51/0.00s info] Using agent test file tests/wrong_param/Then.agent.test.nut
[+545.65/0.14s info] Using device F - Imp001+env (237d606938a609ee) [237d606938a609ee] (1/1)
[+545.78/0.13s info] Using model Test Group B [qryDFGlK1tUd]
[+546.30/0.53s info] Created revision: 104
[+546.76/0.46s info] Device code space usage: 0.5%
[+548.58/1.82s test] Then::testWrongCount()
[+548.58/0.00s test] Success
[+548.58/0.00s test] Then::testWrongFirst_1()
[+549.20/0.61s test] Failure: Fail with value='false'
[+549.20/0.00s test] Then::testWrongFirst_2()
[+549.20/0.00s test] Failure: Fail with value='0'
[+549.20/0.00s test] Then::testWrongFirst_3()
[+549.20/0.00s test] Failure: Fail with value='tmp'
[+549.20/0.00s test] Then::testWrongFirst_4()
[+549.20/0.00s test] Failure: Fail with value='(null : (nil))'
[+549.20/0.00s test] Then::testWrongFirst_5()
[+549.20/0.00s test] Failure: Fail with value='(table : 0x7f14609b86e0)'
[+549.20/0.00s test] Then::testWrongFirst_6()
[+549.20/0.00s test] Failure: Fail with value='(meta : 0x7f142c961a80)'
[+549.20/0.00s test] Then::testWrongSecond_1()
[+549.20/0.00s test] Failure: Fail with value='false'
[+549.20/0.00s test] Then::testWrongSecond_2()
[+549.56/0.36s test] Failure: Fail with value='0'
[+549.56/0.00s test] Then::testWrongSecond_3()
[+549.56/0.00s test] Failure: Fail with value='tmp'
[+549.56/0.00s test] Then::testWrongSecond_4()
[+549.56/0.00s test] Failure: Fail with value='(null : (nil))'
[+549.56/0.00s test] Then::testWrongSecond_5()
[+549.56/0.00s test] Failure: Fail with value='(table : 0x7f1438207af0)'
[+549.56/0.00s test] Then::testWrongSecond_6()
[+549.56/0.00s test] Failure: Fail with value='(meta : 0x7f142c961a80)'
[+549.57/0.00s test] Tests: 13, Assertions: 0, Failures: 12
[+549.57/0.00s info] Session treated-part failed
```

**Comment by dbukhmastov** [comment]
About "And this one times out:" - The test is passed but without log.

#require "Promise.class.nut:3.0.0"
Promise(function(ok, err) {
    ok("Passed: " + blob(4));
}).then(function(res) {
    server.log("Ok");
    server.log(res);
}, function(res) {
    server.log("Err");
    server.log(res);
});

LOG:
2017-03-05 21:45:03 UTC+3 	[Agent] 	Ok
2017-03-05 21:45:03 UTC+3 	[Agent] 	binary: 50 61 73 73 65 64 3a 20 00 00 00 00

server.log("Passed: " + blob(4)) -> binary: 50 61 73 73 65 64 3a 20 00 00 00 00

**Comment by dbukhmastov** [comment]
All tests with known(reported) failures have been disabled. Locally all tests are passed.

**Pull request merged**
